### ISSUE TITLE
On linux, invoking the tool after exporting the binary results in NPE

### ISSUE THREAD

**Issue by coljac** [blurfl/makeUF2-tool#1]
**Describe the bug**

When trying to use the tool  from the Arduino IDE it throws a NullPointerException. I am using Linux, Ubuntu 20.04 64-bit, Arduino 1.8.8 and 1.8.16 both exhibit this behaviour.

**To Reproduce**
Export binary
Invoke tool
A 0-byte uf2 is produced and the following stack trace appears:

```
java.lang.NullPointerException
	at java.lang.Long.decode(Long.java:892)
	at com.makeUF2.makeUF2.makeUF2.createUF2(makeUF2.java:232)
	at com.makeUF2.makeUF2.makeUF2.run(makeUF2.java:290)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
 Create Failed!
```

**Comment by VerbTheNoun95** [comment]
Getting the same thing on macOS 11 using Arduino IDE 1.8.13. My guess is this only works with Arduino 1.8.8, which I can't get working on macOS 11.

**Comment by MattMills** [comment]
Same result on Windows.

**Comment by kgolger** [comment]
Same result on W10 Pro and Arduino IDE 1.8.18...
